# _config.yml

# The main hostname of your site (omit any trailing slash)
url: "https://vistia-ai.github.io"

# The base path where your project is served
# Include a leading slash, but no trailing slash
baseurl: "/backtest"

# (Optional) Additional site metadata
title: "Vistia Backtest Reports"
description: "Backtest report pages for trading strategies"
